#
# microos-rebase-tools
# Copyright (C) 2023  Eugenio Paolantonio <me@medesimo.eu>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

Name:           microos-rebase-tools
Version:        0.0.1
Release:        0
License:        GPL-2.0+
Summary:        Tools to aid rebasing of MicroOS installations
BuildRequires:  make
Requires:       etcrebase
Requires:       python3-kiwi
Requires:       podman

%description
microos-rebase-tools are a set of tools that can reinstall a MicroOS system in-place,
either via an autogenerated kiwi config, via a custom one, from a tarball containing
the new rootfs or from an OCI registry.

%install
make install DESTDIR=%{buildroot}

%files
%defattr(-,root,root)
%{_sbindir}/microos-rebase
%dir /usr/lib/%{name}
/usr/lib/%{name}/*

%changelog